### ISSUE TITLE
Update to Version 2.4

### ISSUE THREAD

**Issue by mizokiPoloci** [maikmerten/bbb-downloader#5]
Hi 
Can you please help me to update the player? i need the new features.

**Comment by maikmerten** [comment]
I haven't yet identified the new player code in the BigBlueButton codebase. The one in https://github.com/bigbluebutton/bigbluebutton/tree/develop/record-and-playback/presentation/playback/presentation/2.0 seems to be the old one without added features.

Once I have time to have a deeper look I'll try to identify and adapt the new player code.

**Comment by maikmerten** [comment]
Okay, I see that the new playback code is over at https://github.com/bigbluebutton/bbb-playback

Sadly, the playback code generated for deployment includes absolute hardcoded paths (in JS, CSS, JSON and HTML files) that just won't work properly for bbb-downloader as-is.

**Comment by maikmerten** [comment]
Thankfully, bbb-playback has an option to generate compiles for stand-alone hosting. Thanks BBB-Team!

**Comment by mizokiPoloci** [comment]
Thank you for your Response,
Would be great if you attach a prebuilt jar file after changes you have done.

**Comment by maikmerten** [comment]
Perhaps this works for you. 
[bbb-download-1.1-SNAPSHOT.jar.zip](https://github.com/maikmerten/bbb-downloader/files/7888808/bbb-download-1.1-SNAPSHOT.jar.zip)

**Comment by mizokiPoloci** [comment]
Yep
That's exactly what it should be.
